#pragma once

#define CBL_FIELD_FLAG_NONE		(uint32_t)0x0
#define CBL_FIELD_FLAG_VARLEN	(uint32_t)0x80
#define CBL_FIELD_FLAG_BINARY	(uint32_t)0x100
#define CBL_FIELD_FLAG_AUTOTRIM	(uint32_t)0x200

#define CBL_FIELD_IS_VARLEN(_F)   (_F & CBL_FIELD_FLAG_VARLEN)
#define CBL_FIELD_IS_BINARY(_F)   (_F & CBL_FIELD_FLAG_BINARY)
#define CBL_FIELD_IS_AUTOTRIM(_F) (_F & CBL_FIELD_FLAG_AUTOTRIM)